### ISSUE TITLE
Handle self signed certificates without a CA

### ISSUE THREAD

**Issue by jacobtomlinson** [kr8s-org/kr8s#139]
### Which project are you reporting a bug for?

kr8s

### What happened?

In https://github.com/dask/dask-kubernetes/issues/803 we see a case where the Kubernetes API server is using a self-signed certificate but the Kubernetes config only uses a token and does not have any CA or cert chain configured so we can't verify the identity of the server.

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://rancher.server/k8s/clusters/...
  name: dev
contexts:
- context:
    cluster: dev
    namespace: dask-operator
    user: dev
  name: dev
current-context: dev
kind: Config
preferences: {}
users:
- name: dev
  user:
    token: kubeconfig-u-...
```

This results in `httpx` raising an `SSLCertVerificationError` exception.

In a case where we have a token and no certificate information we should set SSL verification to False.

### Anything else?

cc @dbalabka
