### ISSUE TITLE
`httpx.HTTPStatusError: Client error '401 Unauthorized'` error when authorizing

### ISSUE THREAD

**Issue by EthanMarx** [kr8s-org/kr8s#214]
### Which project are you reporting a bug for?

kr8s

### What happened?

Hello!

I have been running into an issue where simple use of `kr8s`, e.g.
```python
import kr8s
api = kr8s.api(kubeconfig="~/.kube/config")
kr8s.get("pods", api=api, namespace="bbhnet")
```

gives the following error
```
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://67.58.53.147:6443/api/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
```

However, the equivalent `kubectl` command runs just fine:
```
kubectl get pods
```

Additionally, the error will suddenly go away after some time after repeated calls to the above snippet. 

Any help will be appreciated!

**Comment by jacobtomlinson** [comment]
Could you share the output of `kubectl config view` (please ensure all the secrets are removed)?

**Comment by EthanMarx** [comment]
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://67.58.53.147:6443
  name: nautilus
contexts:
- context:
    cluster: nautilus
    namespace: bbhnet
    user: http://cilogon.org/serverA/users/93606
  name: nautilus
current-context: nautilus
kind: Config
preferences: {}
users:
- name: http://cilogon.org/serverA/users/93606
  user:
    auth-provider:
      config:
        client-id: 
        client-secret: 
        id-token: 
        idp-issuer-url: https://cilogon.org
        refresh-token: NB2HI4DTHIXS6Y3JNRXWO33OFZXXEZZPN5QXK5DIGIXTIZTFMEZGENZRMY4DOY3FMIYDMZBSMYYTENBTGE4GENJUGA2TSNB7OR4XAZJ5OJSWM4TFONUFI33LMVXCM5DTHUYTOMBQGU4TSMZYGA2TSOJGOZSXE43JN5XD25RSFYYCM3DJMZSXI2LNMU6TENJZGIYDAMBQGAYA
      name: oidc
```
