### ISSUE TITLE
Support client-certificate and client-key fields in kubeconfig

### ISSUE THREAD

**Issue by mauriciomem** [kr8s-org/kr8s#263]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

Hi! To expand the scope of what authentication alternatives are supported by k8rs auth process, it would be useful to add support for the client-certificate and client-key kubeconfig fields in [_auth.py ](https://github.com/kr8s-org/kr8s/blob/main/kr8s/_auth.py).

Example tested on minikube 1.32.0 with a k8s cluster running with ver 1.28.0

Any statement that involves auth against the cluster returns the error pasted below:

_kr8s._exceptions.ServerError: nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope_

Old kubeconfig

```
$ k config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/user/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 27 Dec 2023 10:12:42 CET
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: k8s
contexts:
- context:
    cluster: k8s
    extensions:
    - extension:
        last-update: Wed, 27 Dec 2023 10:12:42 CET
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: context_info
    namespace: default
    user: k8s
  name: k8s
current-context: k8s
kind: Config
preferences: {}
users:
- name: k8s
  user:
    client-certificate: /home/user/.minikube/profiles/k8s/client.crt
    client-key: /home/user/.minikube/profiles/k8s/client.key
```

Replacing the client-certificate and client-key fields with their corresponding data counterparts and adjusting the certificates to support pem encoded data (ex `cat /home/user/.certs/client.crt | base64 | tr -d '\n'`) works perfectly.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    extensions:
    - extension:
        last-update: Wed, 27 Dec 2023 10:12:42 CET
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: k8s
contexts:
- context:
    cluster: k8s
    extensions:
    - extension:
        last-update: Wed, 27 Dec 2023 10:12:42 CET
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: context_info
    namespace: default
    user: k8s
  name: k8s
current-context: k8s
kind: Config
preferences: {}
users:
- name: k8s
  user:
    client-certificate-data: ...
    client-key-data: ...
```
